import mongoose from 'mongoose'
const { Schema, model } = mongoose
const money = { type: Number, required: true, min: 0 }
const timestamped = { timestamps: true, versionKey: false }

const counterSchema = new Schema({ key:{type:String,required:true,unique:true}, sequence:{type:Number,default:0} }, { versionKey:false })
const Counter = mongoose.models.Counter || model('Counter', counterSchema)
const supplierSchema = new Schema({ supplierId:{type:String,unique:true,index:true}, name:{type:String,required:true,trim:true}, contactNumber:{type:String,trim:true}, whatsapp:{type:String,trim:true}, address:{type:String,trim:true}, companyName:{type:String,trim:true}, notes:{type:String,trim:true}, outstandingBalance:{type:Number,default:0,min:0}, isActive:{type:Boolean,default:true} }, timestamped)
supplierSchema.pre('validate', async function(){if(!this.isNew||this.supplierId)return;const counter=await Counter.findOneAndUpdate({key:'supplierId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.supplierId=`AKS-${String(counter.sequence).padStart(6,'0')}`})
export const Supplier = model('Supplier', supplierSchema)
const employeeSchema = new Schema({ employeeId:{type:String,unique:true,index:true}, name:{type:String,required:true,trim:true}, cnic:{type:String,trim:true}, phone:{type:String,trim:true}, whatsapp:{type:String,trim:true}, address:{type:String,trim:true}, joiningDate:{type:Date,required:true}, position:{type:String,required:true,trim:true}, dailySalary:{type:Number,required:true,min:0}, monthlySalary:{type:Number,min:0}, photoUrl:{type:String,trim:true}, status:{type:String,enum:['Active','Inactive'],default:'Active'} }, timestamped)
employeeSchema.pre('validate',async function(){if(!this.isNew||this.employeeId)return;const counter=await Counter.findOneAndUpdate({key:'employeeId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.employeeId=`AKE-${String(counter.sequence).padStart(6,'0')}`})
export const Employee = model('Employee', employeeSchema)
const attendanceSchema = new Schema({ attendanceId:{type:String,unique:true,index:true}, employee:{type:Schema.Types.ObjectId,ref:'Employee',required:true}, attendanceDate:{type:Date,required:true}, checkInTime:{type:String,trim:true}, checkOutTime:{type:String,trim:true}, workingHours:{type:Number,default:0,min:0}, status:{type:String,enum:['Present','Absent','Leave','Half Day'],required:true}, overtimeHours:{type:Number,default:0,min:0}, attendanceNotes:{type:String,trim:true}, isActive:{type:Boolean,default:true}, createdBy:{type:Schema.Types.ObjectId,ref:'User'},
  // Set only when a cashier marks attendance during their own shift — lets
  // the shift report show exactly who they marked. Optional/undefined for
  // Admin-entered records, so existing rows are unaffected.
  shift:{type:Schema.Types.ObjectId,ref:'Shift'} }, timestamped)
attendanceSchema.index({employee:1,attendanceDate:1},{unique:true,partialFilterExpression:{isActive:true}})
attendanceSchema.pre('validate',async function(){if(!this.isNew||this.attendanceId)return;const counter=await Counter.findOneAndUpdate({key:'attendanceId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.attendanceId=`AKA-${String(counter.sequence).padStart(6,'0')}`})
export const Attendance = model('Attendance', attendanceSchema)
const shiftSchema = new Schema({ shiftId:{type:String,unique:true,index:true}, cashier:{type:Schema.Types.ObjectId,ref:'User',required:true}, shiftNumber:{type:Number,required:true,min:1,max:20},
  // Admin-assigned schedule window. Optional on the schema so shifts created
  // before this feature existed (no scheduling fields) keep working exactly
  // as before — see shiftService.isWithinWindow for the compatibility rule.
  scheduledDate:{type:Date}, scheduledStartTime:{type:Date}, scheduledEndTime:{type:Date}, assignedBy:{type:Schema.Types.ObjectId,ref:'User'},
  // Actual open/close timestamps, only set once the cashier really starts/ends the shift.
  shiftStartTime:{type:Date}, shiftEndTime:{type:Date}, openingCash:{type:Number,min:0}, closingCash:{type:Number,min:0}, systemCashCollection:{type:Number,default:0,min:0}, expectedCash:{type:Number,default:0,min:0}, cashDifference:{type:Number,default:0}, totalOrders:{type:Number,default:0,min:0}, totalPayments:{type:Number,default:0,min:0}, notes:{type:String,trim:true}, status:{type:String,enum:['Scheduled','Open','Closed','Cancelled'],default:'Scheduled'}, reopenedAt:Date, createdBy:{type:Schema.Types.ObjectId,ref:'User'} },timestamped)
shiftSchema.index({cashier:1,status:1},{unique:true,partialFilterExpression:{status:'Open'}})
shiftSchema.pre('validate',async function(){if(!this.isNew||this.shiftId)return;const counter=await Counter.findOneAndUpdate({key:'shiftId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.shiftId=`AKSH-${String(counter.sequence).padStart(6,'0')}`})
export const Shift = model('Shift',shiftSchema)
const dailyClosingSchema = new Schema({ closingId:{type:String,unique:true,index:true}, closingDate:{type:Date,required:true,unique:true}, closingTime:{type:Date,default:Date.now}, generatedBy:{type:Schema.Types.ObjectId,ref:'User',required:true}, status:{type:String,enum:['Open','Closed'],default:'Open'}, snapshot:{type:Schema.Types.Mixed,required:true}, lockedAt:Date, unlockedAt:Date },timestamped)
dailyClosingSchema.pre('validate',async function(){if(!this.isNew||this.closingId)return;const counter=await Counter.findOneAndUpdate({key:'dailyClosingId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.closingId=`AKDC-${String(counter.sequence).padStart(6,'0')}`})
export const DailyClosing = model('DailyClosing',dailyClosingSchema)
const goatDetailsSchema = new Schema({ goatId:{type:String,trim:true}, tagNumber:{type:String,trim:true}, breed:{type:String,trim:true}, color:{type:String,trim:true}, weight:{type:Number,min:0}, age:{type:String,trim:true}, gender:{type:String,enum:['Male','Female']}, purchasePrice:{type:Number,min:0}, sellingPrice:{type:Number,min:0}, healthStatus:{type:String,trim:true}, notes:{type:String,trim:true} },{_id:false})
const inventoryItemSchema = new Schema({ itemId:{type:String,unique:true,index:true}, itemName:{type:String,required:true,trim:true}, category:{type:String,required:true,trim:true}, quantity:{type:Number,default:0,min:0}, unit:{type:String,required:true,enum:['Kg','Piece','Bag','Liter'],trim:true},
  // Running totals of incoming stock recorded in each unit, tracked independently
  // of the legacy quantity/unit pair above (which stays authoritative for
  // low-stock alerts and order availability, unchanged for backward compatibility).
  stockPieces:{type:Number,default:0,min:0}, stockKg:{type:Number,default:0,min:0},
  lowStockThreshold:{type:Number,default:0,min:0}, imageUrl:{type:String,trim:true}, goatDetails:goatDetailsSchema, isActive:{type:Boolean,default:true} }, timestamped)
inventoryItemSchema.pre('validate', async function(){ if(!this.isNew || this.itemId)return;const counter=await Counter.findOneAndUpdate({key:'inventoryItemId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.itemId=`AKI-${String(counter.sequence).padStart(6,'0')}` })
export const InventoryItem = model('InventoryItem', inventoryItemSchema)
export const Purchase = model('Purchase', new Schema({ date:{type:Date,required:true}, item:{type:Schema.Types.ObjectId,ref:'InventoryItem',required:true},
  // New dual-unit incoming stock fields — both optional individually, at
  // least one enforced in the controller. Legacy quantity/unit are kept but
  // no longer required, purely so old Purchase documents still read back fine.
  quantityPieces:{type:Number,min:0}, quantityKg:{type:Number,min:0},
  quantity:{type:Number,min:0}, unit:{type:String}, purchasePrice:{type:Number,min:0}, totalPrice:{type:Number,min:0}, supplier:{type:Schema.Types.ObjectId,ref:'Supplier',required:true}, invoiceNo:String, notes:String, createdBy:{type:Schema.Types.ObjectId,ref:'User'},
  // Set when a cashier records this during their own shift, for shift-report scoping. Optional/undefined otherwise.
  shift:{type:Schema.Types.ObjectId,ref:'Shift'} }, timestamped))
export const StockUsage = model('StockUsage', new Schema({ date:{type:Date,required:true}, item:{type:Schema.Types.ObjectId,ref:'InventoryItem',required:true}, quantityUsed:{type:Number,required:true,min:0}, purpose:{type:String,required:true,trim:true}, remarks:String, createdBy:{type:Schema.Types.ObjectId,ref:'User'} }, timestamped))
export const StockAdjustment = model('StockAdjustment', new Schema({ date:{type:Date,required:true}, item:{type:Schema.Types.ObjectId,ref:'InventoryItem',required:true}, adjustmentType:{type:String,enum:['Increase','Decrease'],required:true}, quantity:{type:Number,required:true,min:0}, reason:{type:String,required:true,trim:true}, createdBy:{type:Schema.Types.ObjectId,ref:'User'} }, timestamped))
export const SupplierPayment = model('SupplierPayment', new Schema({ supplier:{type:Schema.Types.ObjectId,ref:'Supplier',required:true}, paymentDate:{type:Date,required:true}, amount:money, paymentMethod:{type:String,enum:['Cash','Bank','JazzCash','EasyPaisa','Other'],required:true}, notes:{type:String,trim:true}, createdBy:{type:Schema.Types.ObjectId,ref:'User'} }, timestamped))
const orderItemSchema = new Schema({ inventoryItem:{type:Schema.Types.ObjectId,ref:'InventoryItem',required:true}, itemId:{type:String,required:true}, itemName:{type:String,required:true}, goatDetails:goatDetailsSchema, quantity:{type:Number,required:true,min:1}, unitPrice:{type:Number,required:true,min:0} },{_id:false})
const orderSchema = new Schema({ orderId:{type:String,unique:true,index:true}, orderNumber:{type:String,unique:true}, bookingDate:{type:Date,required:true}, deliveryDate:Date, customer:{type:Schema.Types.ObjectId,ref:'Customer',required:true}, items:{type:[orderItemSchema],validate:v=>v.length>0}, totalAmount:money, advancePaid:{type:Number,default:0,min:0}, remainingAmount:{type:Number,default:0,min:0}, paymentStatus:{type:String,enum:['Paid','Partial','Pending'],default:'Pending'}, paymentMethod:{type:String,enum:['Cash','Bank','JazzCash','EasyPaisa','Other'],required:true}, status:{type:String,enum:['Pending','Confirmed','Completed','Delivered','Cancelled'],default:'Pending'}, notes:{type:String,trim:true}, inventoryDeducted:{type:Boolean,default:false}, shift:{type:Schema.Types.ObjectId,ref:'Shift'}, createdBy:{type:Schema.Types.ObjectId,ref:'User'} }, timestamped)
orderSchema.pre('validate',async function(){if(!this.isNew||this.orderId)return;const counter=await Counter.findOneAndUpdate({key:'orderId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.orderId=`AKO-${String(counter.sequence).padStart(6,'0')}`;this.orderNumber=this.orderId})
export const Order = model('Order', orderSchema)
const paymentSchema = new Schema({ paymentId:{type:String,unique:true,index:true}, customer:{type:Schema.Types.ObjectId,ref:'Customer',required:true}, order:{type:Schema.Types.ObjectId,ref:'Order',required:true}, shift:{type:Schema.Types.ObjectId,ref:'Shift'}, amount:money, paymentMethod:{type:String,enum:['Cash','Bank','JazzCash','EasyPaisa','Other'],required:true}, paymentType:{type:String,enum:['Advance','Partial','Final','Refund'],required:true}, transactionReference:{type:String,trim:true}, paymentNotes:{type:String,trim:true}, date:{type:Date,required:true}, remainingBalance:{type:Number,required:true,min:0}, paymentStatus:{type:String,enum:['Paid','Partial','Pending'],required:true}, receivedBy:{type:Schema.Types.ObjectId,ref:'User'}, isVoided:{type:Boolean,default:false} }, timestamped)
paymentSchema.pre('validate',async function(){if(!this.isNew||this.paymentId)return;const counter=await Counter.findOneAndUpdate({key:'paymentId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.paymentId=`AKP-${String(counter.sequence).padStart(6,'0')}`})
export const Payment = model('Payment', paymentSchema)
const expenseSchema = new Schema({ expenseId:{type:String,unique:true,index:true}, expenseDate:{type:Date,required:true}, category:{type:String,enum:['Electricity','Transport','Fuel','Rent','Maintenance','Miscellaneous','Other'],required:true}, title:{type:String,required:true,trim:true}, description:{type:String,trim:true}, amount:money, paymentMethod:{type:String,enum:['Cash','Bank','JazzCash','EasyPaisa','Other'],required:true}, attachmentUrl:{type:String,trim:true}, notes:{type:String,trim:true}, status:{type:String,enum:['Active','Voided'],default:'Active'}, createdBy:{type:Schema.Types.ObjectId,ref:'User'} }, timestamped)
expenseSchema.pre('validate',async function(){if(!this.isNew||this.expenseId)return;const counter=await Counter.findOneAndUpdate({key:'expenseId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.expenseId=`AKEXP-${String(counter.sequence).padStart(6,'0')}`})
export const Expense = model('Expense', expenseSchema)
const salarySchema = new Schema({ salaryId:{type:String,unique:true,index:true}, employee:{type:Schema.Types.ObjectId,ref:'Employee',required:true}, salaryDate:{type:Date,required:true}, period:{type:String,enum:['Daily','Weekly','Monthly'],required:true}, periodStart:{type:Date,required:true}, periodEnd:{type:Date,required:true}, attendanceSnapshot:{presentDays:{type:Number,default:0},absentDays:{type:Number,default:0},leaveDays:{type:Number,default:0},halfDays:{type:Number,default:0},overtimeHours:{type:Number,default:0}}, dailySalaryRate:{type:Number,required:true,min:0}, monthlySalary:{type:Number,min:0}, overtimeAmount:{type:Number,default:0,min:0}, bonus:{type:Number,default:0,min:0}, deduction:{type:Number,default:0,min:0}, grossSalary:{type:Number,required:true,min:0}, netSalary:{type:Number,required:true,min:0}, paymentMethod:{type:String,enum:['Cash','Bank','JazzCash','EasyPaisa','Other'],required:true}, paymentStatus:{type:String,enum:['Paid','Unpaid','Partial'],default:'Unpaid'}, paidAmount:{type:Number,default:0,min:0}, transactionReference:{type:String,trim:true}, salaryNotes:{type:String,trim:true}, isVoided:{type:Boolean,default:false}, createdBy:{type:Schema.Types.ObjectId,ref:'User'} }, timestamped)
salarySchema.index({employee:1,period:1,periodStart:1,periodEnd:1},{unique:true,partialFilterExpression:{isVoided:false}})
salarySchema.pre('validate',async function(){if(!this.isNew||this.salaryId)return;const counter=await Counter.findOneAndUpdate({key:'salaryId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.salaryId=`AKSAL-${String(counter.sequence).padStart(6,'0')}`})
export const Salary = model('Salary', salarySchema)
const customerSchema = new Schema({ customerId:{type:String,unique:true,index:true}, name:{type:String,required:true,trim:true}, phone:{type:String,trim:true}, whatsapp:{type:String,trim:true}, address:{type:String,trim:true}, city:{type:String,trim:true}, notes:{type:String,trim:true}, pendingBalance:{type:Number,default:0,min:0}, isActive:{type:Boolean,default:true} }, timestamped)
customerSchema.pre('validate', async function(){if(!this.isNew||this.customerId)return;const counter=await Counter.findOneAndUpdate({key:'customerId'},{$inc:{sequence:1}},{upsert:true,new:true,setDefaultsOnInsert:true});this.customerId=`AKC-${String(counter.sequence).padStart(6,'0')}`})
export const Customer = model('Customer', customerSchema)
export const ActivityLog = model('ActivityLog', new Schema({ module:{type:String,required:true}, action:{type:String,required:true}, description:{type:String,required:true}, amount:{type:Number,min:0}, actor:{type:Schema.Types.ObjectId,ref:'User'}, occurredAt:{type:Date,default:Date.now} }, timestamped))
