import mongoose from 'mongoose'
import { ActivityLog, Attendance, Employee } from '../models/BusinessModels.js'
const id=x=>mongoose.isValidObjectId(x);const num=x=>Number(x);const fail=(res,message)=>res.status(400).json({message});const statuses=['Present','Absent','Leave','Half Day'];const log=(data,actor)=>ActivityLog.create({...data,actor})
const day=value=>{const d=new Date(value);d.setHours(0,0,0,0);return d};const hours=(start,end)=>{if(!start||!end)return 0;const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);const result=((eh*60+em)-(sh*60+sm))/60;return result>0?Number(result.toFixed(2)):0}
async function data(input,actor){const {employee,attendanceDate,checkInTime='',checkOutTime='',status,overtimeHours=0,attendanceNotes=''}=input;if(!id(employee)||!attendanceDate||!statuses.includes(status)||!Number.isFinite(num(overtimeHours))||num(overtimeHours)<0)throw new Error('Employee, Attendance Date, valid Attendance Status, and valid Overtime Hours are required.');if((checkInTime&&!checkOutTime)||(!checkInTime&&checkOutTime))throw new Error('Provide both Check-In Time and Check-Out Time together.');const workingHours=hours(checkInTime,checkOutTime);if(checkInTime&&checkOutTime&&!workingHours)throw new Error('Check-Out Time must be later than Check-In Time.');const person=await Employee.findOne({_id:employee,status:'Active'});if(!person)throw new Error('Active employee not found.');return {employee:person,record:{employee:person._id,attendanceDate:day(attendanceDate),checkInTime,checkOutTime,workingHours,status,overtimeHours:num(overtimeHours),attendanceNotes:attendanceNotes.trim(),createdBy:actor}}}
export async function listAttendance(req,res,next){try{const {search='',employee='',status='',fromDate='',toDate='',page=1,limit=31}=req.query;const filter={isActive:true};if(id(employee))filter.employee=employee;if(status)filter.status=status;if(fromDate||toDate)filter.attendanceDate={...(fromDate&&{$gte:day(fromDate)}),...(toDate&&{$lte:new Date(`${toDate}T23:59:59.999Z`)})};const records=await Attendance.find(filter).populate('employee','employeeId name position').sort({attendanceDate:-1}).lean();const matched=search?records.filter(x=>`${x.attendanceId} ${x.employee?.employeeId} ${x.employee?.name}`.toLowerCase().includes(search.toLowerCase())):records;res.json({records:matched.slice((page-1)*limit,page*limit),total:matched.length,page:Number(page),limit:Number(limit)})}catch(error){next(error)}}
export async function attendanceOptions(_,res,next){try{res.json({employees:await Employee.find({status:'Active'}).select('employeeId name position').sort({name:1}).lean()})}catch(error){next(error)}}
export async function createAttendance(req,res,next){try{const parsed=await data(req.body,req.auth.sub);const exists=await Attendance.findOne({employee:parsed.record.employee,attendanceDate:parsed.record.attendanceDate,isActive:true});if(exists)return fail(res,'Attendance has already been recorded for this employee on this date.');const attendance=await Attendance.create(parsed.record);await log({module:'Attendance',action:'Attendance recorded',description:`${attendance.attendanceId} · ${parsed.employee.name} marked ${attendance.status}.`},req.auth.sub);res.status(201).json({attendance})}catch(error){if(error.code===11000)return fail(res,'Duplicate attendance record is not allowed.');if(error.message)return fail(res,error.message);next(error)}}
export async function bulkAttendance(req,res,next){try{if(!Array.isArray(req.body.records)||!req.body.records.length)return fail(res,'One or more attendance records are required.');const prepared=[];for(const input of req.body.records)prepared.push(await data(input,req.auth.sub));const keys=new Set(prepared.map(x=>`${x.record.employee}:${x.record.attendanceDate.toISOString()}`));if(keys.size!==prepared.length)return fail(res,'Duplicate employees are included for the same date.');for(const item of prepared){const exists=await Attendance.findOne({employee:item.record.employee,attendanceDate:item.record.attendanceDate,isActive:true});if(exists)return fail(res,`Attendance already exists for ${item.employee.name} on this date.`)}const entries=await Attendance.insertMany(prepared.map(x=>x.record));await Promise.all(entries.map((entry,index)=>log({module:'Attendance',action:'Bulk attendance recorded',description:`${entry.attendanceId} · ${prepared[index].employee.name} marked ${entry.status}.`},req.auth.sub)));res.status(201).json({records:entries})}catch(error){if(error.message)return fail(res,error.message);next(error)}}
export async function updateAttendance(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid attendance record.');const old=await Attendance.findById(req.params.id);if(!old||!old.isActive)return res.status(404).json({message:'Attendance record not found.'});const parsed=await data(req.body,req.auth.sub);const duplicate=await Attendance.findOne({_id:{$ne:old._id},employee:parsed.record.employee,attendanceDate:parsed.record.attendanceDate,isActive:true});if(duplicate)return fail(res,'Attendance has already been recorded for this employee on this date.');Object.assign(old,parsed.record);await old.save();await log({module:'Attendance',action:'Attendance updated',description:`${old.attendanceId} was corrected for ${parsed.employee.name}.`},req.auth.sub);res.json({attendance:old})}catch(error){if(error.message)return fail(res,error.message);next(error)}}
export async function deactivateAttendance(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid attendance record.');const record=await Attendance.findByIdAndUpdate(req.params.id,{isActive:false},{new:true}).populate('employee','name');if(!record)return res.status(404).json({message:'Attendance record not found.'});await log({module:'Attendance',action:'Attendance voided',description:`${record.attendanceId} for ${record.employee?.name||'employee'} was voided.`},req.auth.sub);res.status(204).end()}catch(error){next(error)}}
export async function monthlySummary(req,res,next){try{const month=req.query.month||new Date().toISOString().slice(0,7);const start=new Date(`${month}-01T00:00:00`),end=new Date(start.getFullYear(),start.getMonth()+1,1);const rows=await Attendance.aggregate([{$match:{isActive:true,attendanceDate:{$gte:start,$lt:end}}},{$group:{_id:{employee:'$employee',status:'$status'},count:{$sum:1},hours:{$sum:'$workingHours'},overtime:{$sum:'$overtimeHours'}}}]);res.json({month,summary:rows})}catch(error){next(error)}}
