import mongoose from 'mongoose'
import { ActivityLog, DailyClosing } from '../models/BusinessModels.js'
import { closingSnapshot } from '../services/dailyClosingService.js'
const id=x=>mongoose.isValidObjectId(x);const fail=(res,message)=>res.status(400).json({message});const day=x=>{const d=new Date(x);d.setHours(0,0,0,0);return d};const log=(data,actor)=>ActivityLog.create({...data,actor})
export async function previewClosing(req,res,next){try{const closingDate=req.query.date||new Date().toISOString().slice(0,10);res.json({snapshot:await closingSnapshot(closingDate)})}catch(error){next(error)}}
export async function listClosings(_,res,next){try{res.json({closings:await DailyClosing.find().populate('generatedBy','name').sort({closingDate:-1}).lean()})}catch(error){next(error)}}
export async function createClosing(req,res,next){try{const closingDate=day(req.body.closingDate||new Date());const existing=await DailyClosing.findOne({closingDate});if(existing&&existing.status==='Closed')return fail(res,'This daily closing is locked. Unlock it before regenerating.');const snapshot=await closingSnapshot(closingDate);const closing=existing?await DailyClosing.findByIdAndUpdate(existing._id,{snapshot,closingTime:new Date(),generatedBy:req.auth.sub},{new:true}):await DailyClosing.create({closingDate,generatedBy:req.auth.sub,snapshot});await log({module:'Daily Closing',action:existing?'Closing recalculated':'Closing generated',description:`${closing.closingId} generated for ${closingDate.toLocaleDateString()}.`,amount:snapshot.financial.netProfit},req.auth.sub);res.status(existing?200:201).json({closing})}catch(error){next(error)}}
export async function lockClosing(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid closing.');const closing=await DailyClosing.findById(req.params.id);if(!closing)return res.status(404).json({message:'Closing not found.'});closing.status='Closed';closing.lockedAt=new Date();await closing.save();await log({module:'Daily Closing',action:'Closing locked',description:`${closing.closingId} was locked.`},req.auth.sub);res.json({closing})}catch(error){next(error)}}
export async function unlockClosing(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid closing.');const closing=await DailyClosing.findById(req.params.id);if(!closing)return res.status(404).json({message:'Closing not found.'});closing.status='Open';closing.unlockedAt=new Date();await closing.save();await log({module:'Daily Closing',action:'Closing unlocked',description:`${closing.closingId} was unlocked.`},req.auth.sub);res.json({closing})}catch(error){next(error)}}
export async function closingDetails(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid closing.');const closing=await DailyClosing.findById(req.params.id).populate('generatedBy','name').lean();if(!closing)return res.status(404).json({message:'Closing not found.'});res.json({closing})}catch(error){next(error)}}
