import mongoose from 'mongoose'
import { ActivityLog, Expense } from '../models/BusinessModels.js'
const id=x=>mongoose.isValidObjectId(x);const n=x=>Number(x);const categories=['Electricity','Transport','Fuel','Rent','Maintenance','Miscellaneous','Other'];const methods=['Cash','Bank','JazzCash','EasyPaisa','Other'];const fail=(res,message)=>res.status(400).json({message});const log=(data,actor)=>ActivityLog.create({...data,actor});const values=body=>({expenseDate:body.expenseDate,category:body.category,title:body.title?.trim(),description:body.description?.trim(),amount:n(body.amount),paymentMethod:body.paymentMethod,attachmentUrl:body.attachmentUrl?.trim(),notes:body.notes?.trim()})
function validate(input){if(!input.expenseDate||!categories.includes(input.category)||!input.title||!Number.isFinite(input.amount)||input.amount<=0||!methods.includes(input.paymentMethod))throw new Error('Expense Date & Time, Category, Expense Title, positive Amount, and Payment Method are required.')}
export async function listExpenses(req,res,next){try{const {search='',category='',fromDate='',toDate='',page=1,limit=25}=req.query;const filter={status:'Active'};if(search)filter.$or=['expenseId','title','description','notes'].map(f=>({[f]:new RegExp(search,'i')}));if(category)filter.category=category;if(fromDate||toDate)filter.expenseDate={...(fromDate&&{$gte:new Date(fromDate)}),...(toDate&&{$lte:new Date(`${toDate}T23:59:59.999Z`)})};const [expenses,total]=await Promise.all([Expense.find(filter).populate('createdBy','name').sort({expenseDate:-1}).skip((Number(page)-1)*Number(limit)).limit(Number(limit)).lean(),Expense.countDocuments(filter)]);res.json({expenses,total})}catch(error){next(error)}}
export async function createExpense(req,res,next){try{const input=values(req.body);validate(input);const expense=await Expense.create({...input,createdBy:req.auth.sub});await log({module:'Expenses',action:'Expense created',description:`${expense.expenseId} · ${expense.title} was recorded.`,amount:expense.amount},req.auth.sub);res.status(201).json({expense})}catch(error){if(error.message)return fail(res,error.message);next(error)}}
export async function updateExpense(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid expense.');const input=values(req.body);validate(input);const expense=await Expense.findOneAndUpdate({_id:req.params.id,status:'Active'},input,{new:true,runValidators:true});if(!expense)return res.status(404).json({message:'Active expense not found.'});await log({module:'Expenses',action:'Expense updated',description:`${expense.expenseId} · ${expense.title} was updated.`,amount:expense.amount},req.auth.sub);res.json({expense})}catch(error){if(error.message)return fail(res,error.message);next(error)}}
export async function expenseDetails(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid expense.');const expense=await Expense.findById(req.params.id).populate('createdBy','name').lean();if(!expense)return res.status(404).json({message:'Expense not found.'});res.json({expense})}catch(error){next(error)}}
export async function voidExpense(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid expense.');const expense=await Expense.findOneAndUpdate({_id:req.params.id,status:'Active'},{status:'Voided'},{new:true});if(!expense)return res.status(404).json({message:'Active expense not found.'});await log({module:'Expenses',action:'Expense voided',description:`${expense.expenseId} · ${expense.title} was voided.`,amount:expense.amount},req.auth.sub);res.status(204).end()}catch(error){next(error)}}
