import mongoose from 'mongoose'
import { ActivityLog, Customer, Order, Payment } from '../models/BusinessModels.js'
import { operationalShift } from '../services/shiftService.js'
const id=x=>mongoose.isValidObjectId(x);const num=x=>Number(x);const fail=(res,message)=>res.status(400).json({message});const methods=['Cash','Bank','JazzCash','EasyPaisa','Other'];const types=['Advance','Partial','Final','Refund'];const log=(data,actor)=>ActivityLog.create({...data,actor})
const paymentStatus=remaining=>remaining===0?'Paid':remaining>0?'Partial':'Pending'
async function refreshCustomer(customer){const orders=await Order.find({customer,status:{$ne:'Cancelled'}}).select('remainingAmount');return Customer.findByIdAndUpdate(customer,{pendingBalance:orders.reduce((sum,x)=>sum+x.remainingAmount,0)})}
export async function listPayments(req,res,next){try{const {search='',paymentMethod='',paymentType='',fromDate='',toDate='',page=1,limit=25}=req.query;const filter={isVoided:false};if(search)filter.paymentId=new RegExp(search,'i');if(paymentMethod)filter.paymentMethod=paymentMethod;if(paymentType)filter.paymentType=paymentType;if(fromDate||toDate)filter.date={...(fromDate&&{$gte:new Date(fromDate)}),...(toDate&&{$lte:new Date(`${toDate}T23:59:59.999Z`)})};
  // Cashiers only ever see payments they themselves received.
  if(req.auth.role==='CASHIER')filter.receivedBy=req.auth.sub
  const [payments,total]=await Promise.all([Payment.find(filter).populate('order','orderId totalAmount remainingAmount status').populate('customer','customerId name phone').populate('receivedBy','name').sort({date:-1,createdAt:-1}).skip((Number(page)-1)*Number(limit)).limit(Number(limit)).lean(),Payment.countDocuments(filter)]);res.json({payments,total,page:Number(page),limit:Number(limit)})}catch(error){next(error)}}
export async function paymentOptions(req,res,next){try{const orders=await Order.find({status:{$nin:['Cancelled']},remainingAmount:{$gt:0}}).populate('customer','customerId name').select('orderId customer remainingAmount totalAmount').sort({createdAt:-1}).lean();res.json({orders})}catch(error){next(error)}}
export async function createPayment(req,res,next){try{const {order,paymentDate,amount,paymentMethod,paymentType,transactionReference,paymentNotes}=req.body;const shift=req.auth.role==='CASHIER'?await operationalShift(req.auth.sub):null;if(req.auth.role==='CASHIER'&&!shift)return fail(res,'You need an open shift within your assigned schedule window before receiving payments.');if(!id(order)||!paymentDate||!methods.includes(paymentMethod)||!types.includes(paymentType)||!Number.isFinite(num(amount))||num(amount)<=0)return fail(res,'Linked Order, Payment Date, positive Amount, Payment Method, and Payment Type are required.');if(paymentType==='Refund'&&req.auth.role!=='ADMIN')return res.status(403).json({message:'Only Admin users can process refunds.'});const booking=await Order.findById(order);if(!booking||booking.status==='Cancelled')return fail(res,'A valid non-cancelled order is required.');let remaining;if(paymentType==='Refund'){const paymentTotals=await Payment.aggregate([{$match:{order:booking._id,isVoided:false}},{$group:{_id:null,collected:{$sum:{$cond:[{$eq:['$paymentType','Refund']},0,'$amount']}},refunded:{$sum:{$cond:[{$eq:['$paymentType','Refund']},'$amount',0]}}}}]);const refundable=(paymentTotals[0]?.collected||0)-(paymentTotals[0]?.refunded||0);if(num(amount)>refundable)return fail(res,'Refund Amount cannot exceed collected payment amount.');remaining=booking.remainingAmount+num(amount)}else{if(num(amount)>booking.remainingAmount)return fail(res,'Payment Amount cannot exceed order remaining balance.');remaining=booking.remainingAmount-num(amount)}booking.remainingAmount=remaining;booking.paymentStatus=paymentStatus(remaining);await booking.save();const payment=await Payment.create({customer:booking.customer,order:booking._id,shift:shift?shift._id:undefined,amount:num(amount),paymentMethod,paymentType,date:paymentDate,transactionReference:transactionReference?.trim(),paymentNotes:paymentNotes?.trim(),remainingBalance:remaining,paymentStatus:booking.paymentStatus,receivedBy:req.auth.sub});await refreshCustomer(booking.customer);await log({module:'Payments',action:paymentType==='Refund'?'Refund processed':'Payment received',description:`${payment.paymentId} recorded for ${booking.orderId}.`,amount:num(amount)},req.auth.sub);res.status(201).json({payment,order:booking})}catch(error){next(error)}}
export async function paymentDetails(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid payment.');const payment=await Payment.findById(req.params.id).populate('order').populate('customer','customerId name phone address city').populate('receivedBy','name').lean();if(!payment)return res.status(404).json({message:'Payment not found.'});if(req.auth.role==='CASHIER'&&payment.receivedBy?._id?.toString()!==req.auth.sub)return res.status(403).json({message:'You can only view payments you received.'});const history=await Payment.find({order:payment.order._id,isVoided:false}).sort({date:1,createdAt:1}).lean();res.json({payment,history})}catch(error){next(error)}}
export async function voidPayment(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid payment.');const payment=await Payment.findById(req.params.id);if(!payment||payment.isVoided)return res.status(404).json({message:'Payment not found.'});const order=await Order.findById(payment.order);if(!order)return res.status(404).json({message:'Linked order not found.'});order.remainingAmount+=payment.paymentType==='Refund'?-payment.amount:payment.amount;if(order.remainingAmount<0)order.remainingAmount=0;order.paymentStatus=paymentStatus(order.remainingAmount);await order.save();payment.isVoided=true;await payment.save();await refreshCustomer(order.customer);await log({module:'Payments',action:'Payment voided',description:`${payment.paymentId} was voided for ${order.orderId}.`,amount:payment.amount},req.auth.sub);res.json({payment,order})}catch(error){next(error)}}
