import mongoose from 'mongoose'
import { ActivityLog, Shift } from '../models/BusinessModels.js'
import { activeShift, calculateShift } from '../services/shiftService.js'
const id=x=>mongoose.isValidObjectId(x);const num=x=>Number(x);const fail=(res,message)=>res.status(400).json({message});const log=(data,actor)=>ActivityLog.create({...data,actor})
export async function currentShift(req,res,next){try{res.json({shift:await activeShift(req.auth.sub)})}catch(error){next(error)}}
export async function listShifts(req,res,next){try{const {search='',status='',cashier='',fromDate='',toDate=''}=req.query;const filter={};if(status)filter.status=status;if(id(cashier))filter.cashier=cashier;if(fromDate||toDate)filter.shiftStartTime={...(fromDate&&{$gte:new Date(fromDate)}),...(toDate&&{$lte:new Date(`${toDate}T23:59:59.999Z`)})};const rows=await Shift.find(filter).populate('cashier','name username').sort({shiftStartTime:-1}).lean();const shifts=search?rows.filter(x=>`${x.shiftId} ${x.cashier?.name} ${x.cashier?.username}`.toLowerCase().includes(search.toLowerCase())):rows;res.json({shifts})}catch(error){next(error)}}
export async function startShift(req,res,next){try{const {shiftNumber,openingCash,notes=''}=req.body;if(!Number.isInteger(num(shiftNumber))||num(shiftNumber)<1||num(shiftNumber)>4||!Number.isFinite(num(openingCash))||num(openingCash)<0)return fail(res,'Shift Number (1–4) and non-negative Opening Cash are required.');const existing=await activeShift(req.auth.sub);if(existing)return fail(res,'Cashier already has an active shift.');const shift=await Shift.create({cashier:req.auth.sub,shiftNumber:num(shiftNumber),shiftStartTime:new Date(),openingCash:num(openingCash),notes:notes.trim(),createdBy:req.auth.sub});await log({module:'Shifts',action:'Shift started',description:`${shift.shiftId} · Shift ${shift.shiftNumber} started.`,amount:shift.openingCash},req.auth.sub);res.status(201).json({shift})}catch(error){if(error.code===11000)return fail(res,'Cashier already has an active shift.');next(error)}}
export async function closeShift(req,res,next){try{const {closingCash,notes=''}=req.body;if(!Number.isFinite(num(closingCash))||num(closingCash)<0)return fail(res,'Non-negative Closing Cash is required.');const shift=await activeShift(req.auth.sub);if(!shift)return res.status(404).json({message:'No active shift found.'});shift.shiftEndTime=new Date();Object.assign(shift,await calculateShift(shift));shift.closingCash=num(closingCash);shift.cashDifference=shift.closingCash-shift.expectedCash;shift.notes=notes.trim()||shift.notes;shift.status='Closed';await shift.save();await log({module:'Shifts',action:'Shift closed',description:`${shift.shiftId} closed with a cash difference of ${shift.cashDifference}.`,amount:shift.systemCashCollection},req.auth.sub);res.json({shift})}catch(error){next(error)}}
export async function shiftDetails(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid shift.');const shift=await Shift.findById(req.params.id).populate('cashier','name username').lean();if(!shift)return res.status(404).json({message:'Shift not found.'});res.json({shift})}catch(error){next(error)}}
export async function reopenShift(req,res,next){try{if(!id(req.params.id))return fail(res,'Invalid shift.');const shift=await Shift.findById(req.params.id);if(!shift)return res.status(404).json({message:'Shift not found.'});if(shift.status==='Open')return fail(res,'Shift is already open.');if(await activeShift(shift.cashier))return fail(res,'Cashier already has another active shift.');shift.status='Open';shift.shiftEndTime=undefined;shift.reopenedAt=new Date();await shift.save();await log({module:'Shifts',action:'Shift reopened',description:`${shift.shiftId} was reopened by Admin.`},req.auth.sub);res.json({shift})}catch(error){next(error)}}
