import mongoose from 'mongoose'
import { ActivityLog, Purchase, Supplier, SupplierPayment } from '../models/BusinessModels.js'
const validId=value=>mongoose.isValidObjectId(value);const amount=value=>Number(value);const methods=['Cash','Bank','JazzCash','EasyPaisa','Other'];const required=(res,msg)=>res.status(400).json({message:msg});
const values=body=>({name:body.name?.trim(),contactNumber:body.contactNumber?.trim(),whatsapp:body.whatsapp?.trim(),address:body.address?.trim(),companyName:body.companyName?.trim(),notes:body.notes?.trim(),isActive:body.isActive!==false})
const log=(data,actor)=>ActivityLog.create({...data,actor})
export async function listSuppliers(req,res,next){try{const {search='',status='',page=1,limit=25}=req.query;const filter={};if(search)filter.$or=['name','companyName','contactNumber','whatsapp'].map(field=>({[field]:new RegExp(search,'i')}));if(status==='active')filter.isActive=true;if(status==='inactive')filter.isActive=false;const [suppliers,total]=await Promise.all([Supplier.find(filter).sort({updatedAt:-1}).skip((Number(page)-1)*Number(limit)).limit(Number(limit)).lean(),Supplier.countDocuments(filter)]);res.json({suppliers,total,page:Number(page),limit:Number(limit)})}catch(error){next(error)}}
export async function createSupplier(req,res,next){try{const input=values(req.body);if(!input.name)return required(res,'Supplier Name is required.');const supplier=await Supplier.create(input);await log({module:'Suppliers',action:'Supplier created',description:`${supplier.name} was added as a supplier.`},req.auth.sub);res.status(201).json({supplier})}catch(error){next(error)}}
export async function updateSupplier(req,res,next){try{if(!validId(req.params.id))return required(res,'Invalid supplier.');const input=values(req.body);if(!input.name)return required(res,'Supplier Name is required.');const supplier=await Supplier.findByIdAndUpdate(req.params.id,input,{new:true,runValidators:true});if(!supplier)return res.status(404).json({message:'Supplier not found.'});await log({module:'Suppliers',action:'Supplier updated',description:`${supplier.name} profile was updated.`},req.auth.sub);res.json({supplier})}catch(error){next(error)}}
export async function deactivateSupplier(req,res,next){try{if(!validId(req.params.id))return required(res,'Invalid supplier.');const supplier=await Supplier.findByIdAndUpdate(req.params.id,{isActive:false},{new:true});if(!supplier)return res.status(404).json({message:'Supplier not found.'});await log({module:'Suppliers',action:'Supplier deactivated',description:`${supplier.name} was deactivated.`},req.auth.sub);res.status(204).end()}catch(error){next(error)}}
export async function supplierProfile(req,res,next){try{if(!validId(req.params.id))return required(res,'Invalid supplier.');const supplier=await Supplier.findById(req.params.id).lean();if(!supplier)return res.status(404).json({message:'Supplier not found.'});const [purchases,payments]=await Promise.all([Purchase.find({supplier:supplier._id}).populate('item','itemName itemId').sort({date:-1}).lean(),SupplierPayment.find({supplier:supplier._id}).sort({paymentDate:-1}).lean()]);const purchaseTotal=purchases.reduce((sum,row)=>sum+row.totalPrice,0),paidTotal=payments.reduce((sum,row)=>sum+row.amount,0),outstandingBalance=Math.max(0,purchaseTotal-paidTotal);if(supplier.outstandingBalance!==outstandingBalance)await Supplier.findByIdAndUpdate(supplier._id,{outstandingBalance});res.json({supplier:{...supplier,outstandingBalance},purchaseHistory:purchases,paymentHistory:payments,summary:{purchaseTotal,paidTotal,outstandingBalance}})}catch(error){next(error)}}
export async function addPayment(req,res,next){try{const {paymentDate,amount:paymentAmount,paymentMethod,notes}=req.body;if(!validId(req.params.id))return required(res,'Invalid supplier.');if(!paymentDate||!methods.includes(paymentMethod)||!Number.isFinite(amount(paymentAmount))||amount(paymentAmount)<=0)return required(res,'Payment Date, positive Amount, and Payment Method are required.');const supplier=await Supplier.findById(req.params.id);if(!supplier)return res.status(404).json({message:'Supplier not found.'});const [purchases,payments]=await Promise.all([Purchase.aggregate([{$match:{supplier:supplier._id}},{$group:{_id:null,total:{$sum:'$totalPrice'}}}]),SupplierPayment.aggregate([{$match:{supplier:supplier._id}},{$group:{_id:null,total:{$sum:'$amount'}}}])]);const outstanding=Math.max(0,(purchases[0]?.total||0)-(payments[0]?.total||0));if(amount(paymentAmount)>outstanding)return required(res,'Payment Amount cannot exceed the outstanding balance.');const payment=await SupplierPayment.create({supplier:supplier._id,paymentDate,amount:amount(paymentAmount),paymentMethod,notes:notes?.trim(),createdBy:req.auth.sub});supplier.outstandingBalance=outstanding-amount(paymentAmount);await supplier.save();await log({module:'Suppliers',action:'Supplier payment',description:`Payment received by ${supplier.name}.`,amount:amount(paymentAmount)},req.auth.sub);res.status(201).json({payment,remainingBalance:supplier.outstandingBalance})}catch(error){next(error)}}
