import bcrypt from 'bcryptjs'
import mongoose from 'mongoose'
import User from '../models/User.js'
import { Employee, ActivityLog } from '../models/BusinessModels.js'

const validId = value => mongoose.isValidObjectId(value)
const fail = (res, message) => res.status(400).json({ message })
const audit = (action, description, actor) => ActivityLog.create({ module: 'User Management', action, description, actor })
const safe = user => ({ id:user._id, username:user.username, name:user.name, employee:user.employee, role:user.role, isActive:user.isActive, forceCredentialChange:user.forceCredentialChange, createdAt:user.createdAt, updatedAt:user.updatedAt })

export async function listUsers(req,res,next){try{const {search='',status=''}=req.query;const filter={};if(status==='active')filter.isActive=true;if(status==='inactive')filter.isActive=false;if(search)filter.$or=[{username:new RegExp(search,'i')},{name:new RegExp(search,'i')},{role:new RegExp(search,'i')}];const users=await User.find(filter).populate('employee','employeeId name position').sort({createdAt:-1}).lean();const matched=search?users.filter(x=>`${x.username} ${x.name} ${x.role} ${x.employee?.employeeId||''} ${x.employee?.name||''}`.toLowerCase().includes(search.toLowerCase())):users;res.json({users:matched})}catch(error){next(error)}}
export async function userOptions(_,res,next){try{res.json({employees:await Employee.find({status:'Active'}).select('employeeId name position').sort({name:1}).lean()})}catch(error){next(error)}}
export async function createUser(req,res,next){try{const {username,name,employee,role,password,pin,forceCredentialChange=false}=req.body;if(!username?.trim()||!name?.trim()||!['ADMIN','CASHIER'].includes(role))return fail(res,'Username, name, and valid role are required.');if(employee&&!validId(employee))return fail(res,'Invalid linked employee.');if(employee&&!await Employee.findById(employee))return fail(res,'Linked employee not found.');const data={username:username.trim().toLowerCase(),name:name.trim(),employee:employee||undefined,role,forceCredentialChange:Boolean(forceCredentialChange)};if(role==='ADMIN'){if(!password||password.length<8)return fail(res,'Admin password must contain at least 8 characters.');data.passwordHash=await bcrypt.hash(password,12)}else{if(!/^\d{4,8}$/.test(pin||''))return fail(res,'Cashier PIN must contain 4–8 digits.');data.pinHash=await bcrypt.hash(pin,12)}const user=await User.create(data);await audit('User created',`${user.username} (${user.role}) was created.`,req.auth.sub);res.status(201).json({user:safe(user)})}catch(error){if(error.code===11000)return fail(res,'Username is already in use.');next(error)}}
export async function updateUser(req,res,next){try{if(!validId(req.params.id))return fail(res,'Invalid user.');const {username,name,employee,role,isActive,forceCredentialChange}=req.body;if(role&&!['ADMIN','CASHIER'].includes(role))return fail(res,'Invalid role.');if(employee&&!validId(employee))return fail(res,'Invalid linked employee.');if(employee&&!await Employee.findById(employee))return fail(res,'Linked employee not found.');const update={};if(username)update.username=username.trim().toLowerCase();if(name)update.name=name.trim();if(employee!==undefined)update.employee=employee||undefined;if(role)update.role=role;if(typeof isActive==='boolean')update.isActive=isActive;if(typeof forceCredentialChange==='boolean')update.forceCredentialChange=forceCredentialChange;const user=await User.findByIdAndUpdate(req.params.id,update,{new:true,runValidators:true});if(!user)return res.status(404).json({message:'User not found.'});await audit('User updated',`${user.username} account was updated.`,req.auth.sub);res.json({user:safe(user)})}catch(error){if(error.code===11000)return fail(res,'Username is already in use.');next(error)}}
export async function resetCredentials(req,res,next){try{if(!validId(req.params.id))return fail(res,'Invalid user.');const user=await User.findById(req.params.id).select('+passwordHash +pinHash');if(!user)return res.status(404).json({message:'User not found.'});if(user.role==='ADMIN'){if(!req.body.password||req.body.password.length<8)return fail(res,'New admin password must contain at least 8 characters.');user.passwordHash=await bcrypt.hash(req.body.password,12)}else{if(!/^\d{4,8}$/.test(req.body.pin||''))return fail(res,'New cashier PIN must contain 4–8 digits.');user.pinHash=await bcrypt.hash(req.body.pin,12)}user.forceCredentialChange=req.body.forceCredentialChange!==false;await user.save();await audit('Credentials reset',`${user.username} credentials were reset.`,req.auth.sub);res.status(204).end()}catch(error){next(error)}}