import { useState } from 'react'
import { Routes, Route, Navigate, useNavigate } from 'react-router-dom'
import { ArrowLeft, CheckCircle2, Eye, EyeOff, KeyRound, LockKeyhole, ShieldCheck, UserRound, ChevronRight } from 'lucide-react'
import './App.css'
import api from './lib/api.js'
import Dashboard from './components/Dashboard.jsx'
import Inventory from './components/Inventory.jsx'
import Suppliers from './components/Suppliers.jsx'
import Customers from './components/Customers.jsx'
import Orders from './components/Orders.jsx'
import Payments from './components/Payments.jsx'
import Employees from './components/Employees.jsx'
import Attendance from './components/Attendance.jsx'
import Salaries from './components/Salaries.jsx'
import Expenses from './components/Expenses.jsx'
import Shifts from './components/Shifts.jsx'
import DailyClosing from './components/DailyClosing.jsx'
import Reports from './components/Reports.jsx'
import System from './components/System.jsx'
import UserManagement from './components/UserManagement.jsx'

function App() { const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('akb_user') || 'null')); const logout=()=>{localStorage.removeItem('akb_token');localStorage.removeItem('akb_user');setUser(null)}; return <Routes><Route path="/login" element={user?<Navigate to="/dashboard" replace/>:<Login signedIn={setUser}/>} /><Route path="/dashboard" element={user?<Dashboard user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/inventory" element={user?<Inventory user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/suppliers" element={user?<Suppliers user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/customers" element={user?<Customers user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/orders" element={user?<Orders user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/payments" element={user?<Payments user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/employees" element={user?<Employees user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/attendance" element={user?<Attendance user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/salaries" element={user?<Salaries user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/expenses" element={user?<Expenses user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/shifts" element={user?<Shifts user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/daily-closing" element={user?<DailyClosing user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/reports" element={user?<Reports user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/system" element={user?<System user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/users" element={user?<UserManagement user={user} logout={logout}/>:<Navigate to="/login" replace/>}/><Route path="/" element={<Navigate to={user?'/dashboard':'/login'} replace />} /></Routes> }
function Login({ signedIn }) {
  const navigate = useNavigate(); const [mode, setMode] = useState('admin'), [username, setUsername] = useState(''), [secret, setSecret] = useState(''), [show, setShow] = useState(false), [error, setError] = useState(''), [loading,setLoading]=useState(false)
  const submit = async e => { e.preventDefault();setLoading(true);setError('');try{const {data}=await api.post('/auth/login',{username,password:mode==='admin'?secret:undefined,pin:mode==='cashier'?secret:undefined,role:mode==='admin'?'ADMIN':'CASHIER'});localStorage.setItem('akb_token',data.token);localStorage.setItem('akb_user',JSON.stringify(data.user));signedIn(data.user);navigate('/dashboard')}catch(err){setError(err.response?.data?.message || err.userMessage || 'Unable to sign in. Please try again.')}finally{setLoading(false)} }
  return <div className="auth-page"><section className="auth-side"><div className="auth-brand"><div className="logo">AK</div><div><b>AL KAUSAR</b><span>BAKREY</span></div></div><div className="side-content"><p className="eyebrow">BUSINESS MANAGEMENT SYSTEM</p><h1>Built for every part<br/>of your livestock business.</h1><p className="side-copy">Securely manage records, sales, cash collection, inventory and staff from one professional workspace.</p><div className="feature-list"><p><CheckCircle2/>Role-based access for Owner / Admin and Cashiers</p><p><CheckCircle2/>Secure sessions and protected business records</p><p><CheckCircle2/>Four fixed cashier shifts with individual access</p></div></div><footer>© 2024 AL KAUSAR BAKREY · Business Management System</footer></section><section className="login-panel"><div className="login-box"><div className="mobile-brand"><div className="logo">AK</div><b>AL KAUSAR BAKREY</b></div><p className="eyebrow">SECURE ACCESS</p><h2>Welcome back</h2><p className="sub">Sign in to access your business workspace.</p><div className="role-switch"><button className={mode === 'admin' ? 'selected' : ''} onClick={() => { setMode('admin'); setError(''); setSecret('') }}><ShieldCheck/>Owner / Admin</button><button className={mode === 'cashier' ? 'selected' : ''} onClick={() => { setMode('cashier'); setError(''); setSecret('') }}><UserRound/>Cashier</button></div><form onSubmit={submit}><label>Username<div className="input"><UserRound/><input value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" placeholder={mode === 'admin' ? 'Enter your username' : 'Enter cashier username'} required /></div></label><label>{mode === 'admin' ? 'Password' : 'Numeric PIN'}<div className="input"><KeyRound/><input value={secret} onChange={e => setSecret(e.target.value.replace(mode === 'cashier' ? /\D/g : ''))} type={show ? 'text' : 'password'} inputMode={mode === 'cashier' ? 'numeric' : undefined} maxLength={mode === 'cashier' ? 8 : undefined} autoComplete="current-password" placeholder={mode === 'admin' ? 'Enter your password' : 'Enter your numeric PIN'} required /><button type="button" onClick={() => setShow(!show)}>{show ? <EyeOff/> : <Eye/>}</button></div></label>{error && <p className="error">{error}</p>}<button className="signin" disabled={loading}>{loading?'Signing in…':<>Sign in <ChevronRight size={18}/></>}</button></form><p className="secure"><LockKeyhole size={13}/> Protected with secure authentication</p></div></section></div>
}
export default App
